# Generated by Django 4.2.7 on 2025-06-18 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouvement', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie'), ('Demandée', 'Demandée')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('demandeur', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='products.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'ordering': ['-date'],
            },
        ),
    ]
