# Generated by Django 4.2.7 on 2025-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='date_effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='type_document',
            field=models.CharField(blank=True, choices=[('BR', 'BR'), ('BS', 'BS'), ('BEX', 'BEX')], max_length=10, null=True),
        ),
    ]
