# Generated by Django 4.2.7 on 2025-10-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_mouvement_date_effective_mouvement_type_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='date_effective',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='type_document',
        ),
    ]
