# Generated by Django 4.2.7 on 2025-10-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_mouvement_date_effective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
