# Generated by Django 4.2.7 on 2025-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='export_type',
            field=models.CharField(choices=[('products', 'Produits'), ('groups', 'Groupes'), ('movements', 'Mouvements'), ('stock_report', 'Rapport de stock'), ('movement_report', 'Rapport de mouvements'), ('predictions', 'Prédictions')], max_length=20),
        ),
    ]
