# Generated by Django 4.2.7 on 2025-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0003_alter_exporthistory_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
