# Generated by Django 4.2.7 on 2025-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0005_exporthistory_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='export_type',
            field=models.CharField(choices=[('products', 'Produits'), ('groups', 'Groupes'), ('movements', 'Mouvements'), ('stock_report', 'Rapport de stock'), ('movement_report', 'Rapport de mouvements'), ('complet', 'Export Complet')], max_length=20),
        ),
    ]
