# Generated by Django 4.2.7 on 2025-07-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_format_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_format',
            field=models.CharField(blank=True, default='dd/MM/yyyy', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, default='light', max_length=20),
        ),
    ]
