# Generated by Django 4.2.7 on 2025-07-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_format_alter_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
