# Generated by Django 4.2.7 on 2025-09-01 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_date_format_remove_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password_expiry_days',
            field=models.IntegerField(default=90, help_text='Expiration du mot de passe en jours'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_timeout',
            field=models.IntegerField(default=30, help_text="Délai d'expiration en minutes"),
        ),
    ]
