# Generated by Django 4.2.7 on 2025-08-18 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_produit_stock_initial_fixe_inventaireproduit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=10)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'inventaire",
                'verbose_name_plural': "Sessions d'inventaire",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='AjustementInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantite_physique', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ecart', models.DecimalField(decimal_places=3, max_digits=14)),
                ('date_ajustement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements', to='inventory.sessioninventaire')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ajustement d'inventaire",
                'verbose_name_plural': "Ajustements d'inventaire",
                'ordering': ['-date_ajustement'],
            },
        ),
        migrations.CreateModel(
            name='LigneComptage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_physique', models.DecimalField(decimal_places=3, max_digits=14)),
                ('date_comptage', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptages', to='inventory.sessioninventaire')),
            ],
            options={
                'verbose_name': 'Ligne de comptage',
                'verbose_name_plural': 'Lignes de comptage',
                'indexes': [models.Index(fields=['session', 'produit'], name='inventory_l_session_926ee4_idx')],
                'unique_together': {('session', 'produit')},
            },
        ),
    ]
