# Generated by Django 4.2.7 on 2025-08-19 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_remove_produit_stock_initial_fixe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.IntegerField(default=90, help_text="Fenêtre d'historique en jours")),
                ('forecast_horizon', models.IntegerField(default=30, help_text='Horizon de prévision en jours')),
                ('z_factor', models.DecimalField(decimal_places=2, default=1.65, help_text='Facteur de service (1.65 = 95%)', max_digits=5)),
                ('default_lead_time', models.IntegerField(default=7, help_text='Lead time par défaut en jours')),
                ('urgent_threshold_multiplier', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('monitor_threshold_multiplier', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('min_historical_days_for_confidence', models.IntegerField(default=30)),
                ('min_movements_for_confidence', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration Point de Commande',
                'verbose_name_plural': 'Configurations Point de Commande',
            },
        ),
        migrations.CreateModel(
            name='ReorderMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('urgent_count', models.IntegerField(default=0)),
                ('monitor_count', models.IntegerField(default=0)),
                ('ok_count', models.IntegerField(default=0)),
                ('total_suggested_units', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('draft_orders_created', models.IntegerField(default=0)),
                ('draft_orders_approved', models.IntegerField(default=0)),
                ('batch_execution_time', models.DecimalField(decimal_places=2, help_text='Temps en secondes', max_digits=10, null=True)),
                ('batch_success', models.BooleanField(default=True)),
                ('batch_error_message', models.TextField(blank=True)),
                ('average_confidence', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('low_confidence_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitoring Recommandations',
                'verbose_name_plural': 'Monitoring Recommandations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReorderAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.CharField(default='Principal', max_length=100)),
                ('avg_daily_demand', models.DecimalField(decimal_places=3, help_text='Demande journalière moyenne', max_digits=10)),
                ('sigma_daily_demand', models.DecimalField(decimal_places=3, help_text='Écart-type journalier', max_digits=10)),
                ('lead_time_days', models.IntegerField(help_text='Lead time en jours')),
                ('safety_stock', models.DecimalField(decimal_places=2, help_text='Stock de sécurité', max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=2, help_text='Point de commande', max_digits=10)),
                ('predicted_30d', models.DecimalField(decimal_places=2, help_text='Prévision 30 jours', max_digits=10)),
                ('days_of_coverage', models.DecimalField(decimal_places=2, help_text='Jours de couverture', max_digits=10)),
                ('suggested_qty', models.DecimalField(decimal_places=2, help_text='Quantité suggérée', max_digits=10)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('A_SURVEILLER', 'À Surveiller'), ('URGENT', 'Urgent')], max_length=20)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'Élevée'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], max_length=10)),
                ('confidence_reason', models.TextField(blank=True, help_text='Raison du niveau de confiance')),
                ('calculation_date', models.DateTimeField(auto_now=True)),
                ('window_days_used', models.IntegerField()),
                ('z_factor_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('movements_count', models.IntegerField(help_text='Nombre de mouvements utilisés')),
                ('explanation', models.JSONField(default=dict, help_text='Détails des calculs')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_analyses', to='products.produit')),
            ],
            options={
                'verbose_name': 'Analyse Point de Commande',
                'verbose_name_plural': 'Analyses Point de Commande',
                'ordering': ['-calculation_date', 'status', 'produit__nom'],
                'unique_together': {('produit', 'depot', 'calculation_date')},
            },
        ),
        migrations.CreateModel(
            name='DraftPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('ORDERED', 'Commandé')], default='DRAFT', max_length=20)),
                ('justification', models.TextField(help_text='Justification automatique de la recommandation')),
                ('user_comment', models.TextField(blank=True, help_text='Commentaire utilisateur')),
                ('approval_comment', models.TextField(blank=True, help_text="Commentaire d'approbation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_orders', to='reports.reorderanalysis')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_draft_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_draft_orders', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit')),
            ],
            options={
                'verbose_name': 'Bon de Commande Brouillon',
                'verbose_name_plural': 'Bons de Commande Brouillon',
                'ordering': ['-created_at'],
            },
        ),
    ]
