# Generated by Django 4.2.7 on 2025-09-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftPurchaseOrder',
        ),
    ]
