# Generated by Django 4.2.7 on 2025-06-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='zone',
        ),
    ]
