# Generated by Django 4.2.7 on 2025-06-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_groupe_responsable_remove_groupe_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
    ]
