# Generated by Django 4.2.7 on 2025-08-06 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_remove_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock_initial_fixe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock de référence fixe, mis à jour uniquement après inventaire', max_digits=10),
        ),
        migrations.CreateModel(
            name='InventaireProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_systeme', models.DecimalField(decimal_places=2, help_text="Stock selon le système au moment de l'inventaire", max_digits=10)),
                ('stock_physique', models.DecimalField(decimal_places=2, help_text='Stock compté physiquement', max_digits=10)),
                ('ecart', models.DecimalField(decimal_places=2, help_text='Différence entre stock physique et système', max_digits=10)),
                ('date_inventaire', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('ajustement_effectue', models.BooleanField(default=False, help_text="Indique si l'ajustement de stock a été effectué")),
                ('mouvement_ajustement', models.ForeignKey(blank=True, help_text="Mouvement d'ajustement créé suite à l'inventaire", null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.mouvement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='products.produit')),
                ('utilisateur', models.ForeignKey(help_text="Utilisateur ayant effectué l'inventaire", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire Produit',
                'verbose_name_plural': 'Inventaires Produits',
                'ordering': ['-date_inventaire'],
            },
        ),
    ]
