# Generated by Django 4.2.7 on 2025-08-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_produit_stock_initial_fixe_inventaireproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='stock_initial_fixe',
        ),
    ]
