# Generated by Django 4.2.7 on 2025-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_produit_stock_initial_fixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='lead_time',
            field=models.IntegerField(default=7, help_text='Délai de livraison en jours'),
        ),
    ]
